### ISSUE TITLE
Use docker links instead of IP addressses

### ISSUE THREAD

**Issue by jlk** [plantpark/docker-cluster-with-celery-and-rabbitmq#3]
When I try bringing up the composition with `docker-compose up`, I see:

```
worker_1  | [2017-02-25 18:27:55,224: ERROR/MainProcess] consumer: Cannot connect to amqp://admin:**@10.211.55.12:5672//: timed out.
worker_1  | Trying again in 2.00 seconds...
worker_1  |
```

As docker is giving my rabbitmq container an IP address of 172.25.0.2.

In the docker-compose.yml, you link the worker to rabbitmq:
```
        links:
            - rabbit
```

Now that that's in place, using 'rabbit' instead of an IP address will allow the workers to find the mq without a specific IP address.

**Comment by saiyancode** [comment]
@jlk thanks this massively helped me fix the last bug in my compose file!

**Comment by tonywangcn** [comment]
Thanks. fixed.

**Comment by mrbrazzi** [comment]
If you use **docker swarm** and **docker stack deploy**, the use of **links** is deprecated, instead define **hostname** or use **depends_on**

**Comment by jlk** [comment]
good point.
