### ISSUE TITLE
ERROR: Cannot start service worker

### ISSUE THREAD

**Issue by ilovetogetspamed** [plantpark/docker-cluster-with-celery-and-rabbitmq#5]
bash-3.2$ docker-compose build
rabbit uses an image, skipping
Building worker
Step 1/6 : FROM python:2.7
 ---> bd2db1324f76
Step 2/6 : ADD requirements.txt /app/requirements.txt
 ---> Using cache
 ---> 439a8c60e121
Step 3/6 : ADD ./test_celery/ /app/
 ---> Using cache
 ---> 26662f81caff
Step 4/6 : WORKDIR /app/
 ---> Using cache
 ---> ec3cf5e36baf
Step 5/6 : RUN pip install -r requirements.txt
 ---> Using cache
 ---> 18c4e2113b27
Step 6/6 : ENTRYPOINT celery -A test_celery worker --loglevel=info
 ---> Using cache
 ---> 948573ede93a
Successfully built 948573ede93a
Successfully tagged dockerclusterwithceleryandrabbitmq_worker:latest
bash-3.2$ docker-compose scale worker=5
WARNING: The scale command is deprecated. Use the up command with the --scale flag instead.
Creating dockerclusterwithceleryandrabbitmq_worker_1 ... error
Creating dockerclusterwithceleryandrabbitmq_worker_2 ... error
Creating dockerclusterwithceleryandrabbitmq_worker_3 ... error
Creating dockerclusterwithceleryandrabbitmq_worker_4 ... error
Creating dockerclusterwithceleryandrabbitmq_worker_5 ... error

ERROR: for dockerclusterwithceleryandrabbitmq_worker_4  Cannot start service worker: network dockerclusterwithceleryandrabbitmq_default not found

ERROR: for dockerclusterwithceleryandrabbitmq_worker_5  Cannot start service worker: network dockerclusterwithceleryandrabbitmq_default not found

ERROR: for dockerclusterwithceleryandrabbitmq_worker_1  Cannot start service worker: network dockerclusterwithceleryandrabbitmq_default not found

ERROR: for dockerclusterwithceleryandrabbitmq_worker_2  Cannot start service worker: network dockerclusterwithceleryandrabbitmq_default not found

ERROR: for dockerclusterwithceleryandrabbitmq_worker_3  Cannot start service worker: network dockerclusterwithceleryandrabbitmq_default not found
ERROR: Cannot start service worker: network dockerclusterwithceleryandrabbitmq_default not found

**Comment by tonywangcn** [comment]
plz check the latest commit.
